---
title: "Plots"
author: "Chris Gaskell"
date: "14/08/2021"
output:
  html_document:
    keep_md: yes
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 10, fig.height = 4.7)
library(scan)
library(tidyverse)
library(readxl)
```


```{r data, include=FALSE}

dat <- list(
          dat.AB = readxl::read_xls("data/data.xls", sheet = "AB"),
          dat.ABFU = readxl::read_xls("data/data.xls", sheet = "ABFU"),
          dat.ABABFU = readxl::read_xls("data/data.xls", sheet = "ABABFU"),
          dat.ABCFU = readxl::read_xls("data/data.xls", sheet = "ABCFU"),
          dat.carer = readxl::read_xls("data/data.xls", sheet = "Carer"),
          dat.stability = readxl::read_xls("data/data.xls", sheet = "Stability")
        )

sc.dat <- scan::readSC.excel("data/data.xls",)

```


```{r AB, echo=FALSE}
dat <- data.frame(
        mt = seq(1,56, by=1),
        phase = c(rep("A",14), rep("B",42)),
        values = c(sample(15:30, 14, replace = TRUE), sample(0:15, 42, replace = TRUE))
)

dat <- scan::as_scdf(dat)

newstyle <- style_plot(fill = "grey95", grid = "lightblue", pch = 16
                       )

plotSC(dat, style = newstyle,
       xinc = 5, main = " ",
       xlab = "Days of the study",
       ylab = "Reassurance seeking behaviours",
       phase.names = c("Baseline", "CBT"),
       case.names = " "
          )
    
```

```{r ABFU, echo=FALSE}

dat <- data.frame(
        mt = seq(1,70, by=1),
        phase = c(rep("A",14), rep("B",42), rep("FU",14)),
        values = c(sample(15:30, 14, replace = TRUE), sample(0:15, 42, replace = TRUE), sample(10:21, 14, replace = TRUE))
)

dat <- scan::as_scdf(dat)

newstyle <- style_plot(fill = "grey95", grid = "lightblue", pch = 16
                       )

plotSC(dat, style = newstyle,
       xinc = 5, main = " ",
       xlab = "Days of the study",
       ylab = "Reassurance seeking behaviours",
       phase.names = c("Baseline", "CBT", "Follow Up"),
       case.names = " "
          )
    
```

```{r ABAB, echo=FALSE}

dat <- data.frame(
        mt = seq(1,84, by=1),
        phase = c(rep("A",14), rep("B",28), rep("A",14), rep("B",28)),
        values = c(sample(15:30, 14, replace = TRUE), sample(0:15, 28, replace = TRUE), sample(10:21, 14, replace = TRUE), sample(0:15, 28, replace = TRUE))
)

dat <- scan::as_scdf(dat)

newstyle <- style_plot(fill = "grey95", grid = "lightblue", pch = 16
                       )

plotSC(dat, style = newstyle,
       xinc = 5, main = " ",
       xlab = "Days of the study",
       ylab = "Reassurance seeking behaviours",
       phase.names = c("Baseline", "Graded Exposure", "Withdrawal", "Cognitve Therapy"),
       case.names = " "
          )
    
```

```{r ABAC, echo=FALSE}

dat <- data.frame(
        mt = seq(1,84, by=1),
        phase = c(rep("A",14), rep("B",14), rep("A",42), rep("B",14)),
        values = c(sample(25:30, 14, replace = TRUE), sample(18:23, 14, replace = TRUE), sample(13:18, 42, replace = TRUE), sample(15:20, 14, replace = TRUE))
)

dat <- scan::as_scdf(dat)

newstyle <- style_plot(fill = "grey95", grid = "lightblue", pch = 16
                       )

plotSC(dat, style = newstyle,
       xinc = 5, main = " ",
       xlab = "Days of the study",
       ylab = "Reassurance seeking behaviours",
       phase.names = c("Baseline", "Grounding", "CBT", "Follow Up"),
       case.names = " "
          )
    
```

```{r plot-stability, echo=FALSE}
#plotSC(sc.dat$Sleep, style = newstyle,
#       xinc = 5, xlab = "Days of the study",
#       ylab = "Hour asleep",
#       phase.names = c("Baseline", "Sleep Hygiene")
#          )
```

```{r title-plot, include=F}
#Plot <- ggplot(dat$dat.stability,
#          aes(x = mt, y = values)) +
#          geom_line(aes(color = phase,
#                )) 

```



```{r transition, include=F, fig.width=12, fig.height=5}
dat <- data.frame(
        mt = seq(1,56, by=1),
        phase = c(rep("A",14), rep("B",42)),
        values = c(sample(15:30, 14, replace = TRUE), sample(0:15, 42, replace = TRUE))
)

Plot <- ggplot(dat, aes(x = mt, y = values)) +
          geom_line(aes(color = phase), color="#e5bf00") +
          ylab("Number of checking behaviours")+
          xlab("Days across the study") +
  geom_vline(xintercept = 14.5, color = "white", size=.5, linetype="dashed")+
     annotate("text", x = .5*(0+14), y = 31, label = "Baseline", size=10, colour = "#e5bf00") +
     annotate("text", x = .5*(14+56), y = 31, label = "CBT", size=10, colour = "#e5bf00") + theme(
            plot.background = element_rect(fill = "#122140", colour = NULL, size = 0),
            panel.background =  element_rect(fill = "#122140", colour = "white"), panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
            axis.title=element_text(size=16,face="bold"),
            text = element_text(colour = "white"),
            axis.text = element_text(colour = "#e5bf00", size = rel(1.5))
            ) + geom_point(colour = "white")+ 
      scale_x_continuous(breaks=seq(0,56,5)) +
      scale_y_continuous(breaks=seq(0,30,5)) + gganimate::transition_reveal(mt)

  
gganimate::animate(Plot, height = 300, width =1200)
gganimate::anim_save("title-plot.gif")

```


```{r transition2, include=F, fig.width=12, fig.height=5}
dat <- data.frame(
        mt = seq(1,56, by=1),
        phase = c(rep("A",14), rep("B",42)),
        values = c(sample(15:30, 14, replace = TRUE), sample(0:15, 42, replace = TRUE))
)

Plot <- ggplot(dat, aes(x = mt, y = values)) +
          geom_line(aes(color = phase), color="#e5bf00") +
          ylab("Number of checking behaviours")+
          xlab("Days across the study") +
  geom_vline(xintercept = 14.5, color = "white", size=.5, linetype="dashed")+
     annotate("text", x = .5*(0+14), y = 31, label = "Baseline", size=10, colour = "#e5bf00") +
     annotate("text", x = .5*(14+56), y = 31, label = "CBT", size=10, colour = "#e5bf00") + theme(
            plot.background = element_rect(fill = "#600018", colour = NULL, size = 0),
            panel.background =  element_rect(fill = "#600018", colour = "white"), panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
            axis.title=element_text(size=16,face="bold"),
            text = element_text(colour = "white"),
            axis.text = element_text(colour = "#e5bf00", size = rel(1.5))
            ) + geom_point(colour = "white")+ 
      scale_x_continuous(breaks=seq(0,56,5)) +
      scale_y_continuous(breaks=seq(0,30,5)) + gganimate::transition_reveal(mt)

  
gganimate::animate(Plot, height = 300, width =1200)
gganimate::anim_save("title-plot3.gif")

```